### ISSUE TITLE
Schedule will need R links when instructors decide how they are teaching

### ISSUE THREAD

**Issue by sstevens2** [UW-Madison-DataScience/2019-01-16-uwmadison-dc#6]

**Comment by sstevens2** [comment]
Again no rush right now @ChristinaLK, @mkamenet3. I'm mostly getting myself organized so I don't forget anything.  Feel free to comment here if about the R links if you'd like.

**Comment by sstevens2** [comment]
@mkamenet3 sent me her lessons https://mkamenet3.github.io/datacarpentry_R_2019-01-17/
@ChristinaLK do you want to make a PR on [that repo](https://github.com/mkamenet3/datacarpentry_R_2019-01-17) with your lessons? or have a separate link?

**Comment by ChristinaLK** [comment]
I think I'm going to use the standard curriculum.

**Comment by ChristinaLK** [comment]
https://datacarpentry.org/R-ecology-lesson/

Intro to R until Dataframes

**Comment by sstevens2** [comment]
Awesome! Thanks you two!
