### ISSUE TITLE
Social get-together

### ISSUE THREAD

**Issue by sstevens2** [UW-Madison-DataScience/2019-01-16-uwmadison-dc#7]
Hi all,

We talked about being available for conversation and socialization during lunch both days at the pre-workshop meeting.  Do we still want to plan to have a social at the end of one day too? <- If so, which day would you prefer?

@tadamus, @ChristinaLK, @mkamenet3, Erin Jonatis

Thanks,
Sarah

**Comment by emjonaitis** [comment]
My evenings are going to be pretty busy in January, so the lunch plan works better for me.

**Comment by mkamenet3** [comment]
Lunch plan works for me as well, but I could do the evening of the second day (R day) as well if others are interested.

**Comment by ChristinaLK** [comment]
Thurs is slightly better than Wed.

**Comment by sstevens2** [comment]
I'll go ahead and remove the evening social for this time around and we can discuss if we missed it and how we liked the lunch social at the post workshop debrief.
